name: Deployment Workflow for deploy.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      environment: ${{ secrets.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run deployment script
        run: |
          chmod +x deploy.sh
          ./deploy.sh $environment