name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute Shell Script
        run: |
          chmod +x deploy.sh
          ./deploy.sh dev
          # Use the environment variables in your script