name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variable
        run: |
          echo "MY_ENVIRONMENT=${{ env.MY_ENVIRONMENT }}" >> $GITHUB_ENV

      - name: Run deployment script
        run: |
          echo "Deploying using environment: $MY_ENVIRONMENT"
          # Add your deployment commands here