name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run deployment script
        run: |
          chmod +x deploy.sh
          ./deploy.sh $ENVIRONMENT