name: CI/CD - Development Environment

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Additional steps for building and testing
      - name: Build and test
        run: |
          echo "Building and testing the application"

      - name: Deploy to dev environment
        run: |
          echo "Deploying to dev environment"
          echo "Environment: dev}"