name: CI/CD - Development Environment

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        id: build
        run: |
          echo "Building and testing the application"
          echo "::set-output name=TEST_ENV::dev"
          echo "::set-output name=TEST_ENV_1::dev1"

      - name: Get specific variable value
        run: |
          echo "TEST_ENV: ${{ steps.build.outputs.TEST_ENV }}"
          echo "TEST_ENV_1: ${{ steps.build.outputs.TEST_ENV_1 }}"

      # Additional steps for building and testing
      - name: Build and test
        run: |
          echo "Building and testing the application"
          echo "${{ toJSON(vars) }}"
