name: CI/CD - Development Environment

env: 
  env_var: ${{ vars.MY_ENVIRONMENT }}
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Additional steps for building and testing
      - name: Build and test
        run: |
          echo "Building and testing the application"
          echo "${{ vars.TEST_ENV }}"

      - name: Checkout code
        run: env

      - name: Deploy to dev environment
        run: |
          echo "Deploying to dev environment"
          echo "Environment: dev}"