name: CI/CD - Development Environment

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get specific variable value
        run: |
          echo "TEST_ENV: ${{ steps.build.outputs.TEST_ENV }}"
          echo "TEST_ENV_1: ${{ steps.build.outputs.TEST_ENV_1 }}"

      # Additional steps for building and testing
      - name: Build and test
        run: |
          echo "Building and testing the application"
          echo "${{ toJSON(vars) }}"

      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> "$GITHUB_ENV"
      - name: Use the value
        id: step_two
        run: |
          echo "${{ toJSON(vars.TEST_ENV) }}" # This will output 'yellow'
