name: CI/CD - Production Environment

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Additional steps for building and testing
      - name: Build and test
        run: |
          echo "Building and testing the application"

      - name: Deploy to prod environment
        run: |
          echo "Deploying to prod environment"
          echo "Environment: prod"